### ISSUE TITLE
npm run contract:deploy

### ISSUE THREAD

**Issue by Daniil-9374** [CryptoBlades/cryptoblades#489]
After npm run contract:prepare
When I run npm run contract:deploy, there is one critical issue occurred. I am not sure what is the issue.

Error: Artifacts are from different compiler runs
    Run a full recompilation using `truffle compile --all`
    https://zpl.in/upgrades/truffle-recompile-all
    at checkForImportIdConsistency (D:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\utils\validations.ts:111:15)
    at reconstructSolcInputOutput (D:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\utils\validations.ts:71:3)
    at Object.validateArtifacts (D:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\utils\validations.ts:17:29)
    at Object.deployImpl (D:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\utils\deploy-impl.ts:29:23)
    at deployProxy (D:\Game\cryptoblades\node_modules\@openzeppelin\truffle-upgrades\src\deploy-proxy.ts:46:16)
    at module.exports (D:\Game\cryptoblades\migrations\7_development+bsctestnet_staking.js:16:5)
    at Migration._deploy (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:79:1)
    at Migration._load (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:61:1)
    at Migration.run (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\Migration.js:212:1)
    at Object.runMigrations (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\index.js:150:1)
    at Object.runFrom (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\index.js:110:1)
    at Object.runAll (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\index.js:114:1)
    at Object.run (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\migrate\index.js:79:1)
    at runMigrations (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:263:1)
    at Object.run (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\core\lib\commands\migrate.js:228:1)
    at Command.run (D:\Game\cryptoblades\node_modules\truffle\build\webpack:\packages\core\lib\command.js:136:1)
Truffle v5.2.3 (core: 5.2.3)
Node v14.17.3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kryptoknights@1.0.0 deploy: `truffle migrate --reset`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kryptoknights@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

If you know how to fix it, I hope you to give me any advice.
Thank you in advance.

**Comment by seiyria** [comment]
This does not belong on github, this could have been a question in dev round table. Secondarily, if you look at the readme, you'd see the section for errors: https://github.com/CryptoBlades/cryptoblades#errors
